# TODO enable bochs once the PF bug is fixed
# TODO also stack from dump_state is visible in the result,
# either don't show it or use a different stack in dump_state
DISABLE_BOCHS=1
include ../test.mk
