; ADC 16-bit, no input carry
; TODO

;     clc
;     mov bx, 0x0000
;     mov cx, 0x0000
;     adc bx, cx
;     pushf

;     clc
;     mov cx, 0x0012
;     mov dx, 0x0034
;     adc cx, dx
;     pushf

;     clc
;     mov dx, 0x0050
;     mov bp, 0x002f
;     adc dx, bp
;     pushf

;     clc
;     mov bp, 0x0075
;     mov si, 0x000b
;     adc bp, si
;     pushf

;     clc
;     mov si, 0x0061
;     mov di, 0x0035
;     adc si, di
;     pushf

;     dump_state

;     clc
;     mov bx, 0x0081
;     mov cx, 0x002a
;     adc bx, cx
;     pushf

;     clc
;     mov cx, 0x007d
;     mov dx, 0x0082
;     adc cx, dx
;     pushf

;     clc
;     mov dx, 0x00a9
;     mov bp, 0x0057
;     adc dx, bp
;     pushf

;     clc
;     mov bp, 0x00ec
;     mov si, 0x003b
;     adc bp, si
;     pushf

;     clc
;     mov si, 0x00ba
;     mov di, 0x0089
;     adc si, di
;     pushf

;     dump_state

;     clc
;     mov bx, 0x00ff
;     mov cx, 0x0080
;     adc bx, cx
;     pushf

;     clc
;     mov cx, 0x00ec
;     mov dx, 0x00db
;     adc cx, dx
;     pushf

;     clc
;     mov dx, 0x1234
;     mov bp, 0x5678
;     adc dx, bp
;     pushf

;     clc
;     mov bp, 0x5050
;     mov si, 0x2faf
;     adc bp, si
;     pushf

;     clc
;     mov si, 0x7ff0
;     mov di, 0x0010
;     adc si, di
;     pushf

;     dump_state

;     clc
;     mov bx, 0x6789
;     mov cx, 0x4567
;     adc bx, cx
;     pushf

;     clc
;     mov cx, 0x89ab
;     mov dx, 0x2345
;     adc cx, dx
;     pushf

;     clc
;     mov dx, 0x9abc
;     mov bp, 0x6543
;     adc dx, bp
;     pushf

;     clc
;     mov bp, 0xedcb
;     mov si, 0x5432
;     adc bp, si
;     pushf

;     clc
;     mov si, 0xa987
;     mov di, 0x8765
;     adc si, di
;     pushf

;     dump_state

;     clc
;     mov bx, 0x8003
;     mov cx, 0xfffc
;     adc bx, cx
;     pushf

;     clc
;     mov cx, 0xffff
;     mov dx, 0xffff
;     adc cx, dx
;     pushf

;     dump_state
