; ADC 16-bit, no input carry
; TODO

;     stc
;     mov bx, 0x0000
;     mov cx, 0x0000
;     adc bx, cx
;     pushf

;     stc
;     mov cx, 0x0012
;     mov dx, 0x0033
;     adc cx, dx
;     pushf

;     stc
;     mov dx, 0x0050
;     mov bp, 0x002e
;     adc dx, bp
;     pushf

;     stc
;     mov bp, 0x0075
;     mov si, 0x000a
;     adc bp, si
;     pushf

;     stc
;     mov si, 0x0061
;     mov di, 0x0034
;     adc si, di
;     pushf

;     dump_state

;     stc
;     mov bx, 0x0081
;     mov cx, 0x0029
;     adc bx, cx
;     pushf

;     stc
;     mov cx, 0x007d
;     mov dx, 0x0081
;     adc cx, dx
;     pushf

;     stc
;     mov dx, 0x00a9
;     mov bp, 0x0056
;     adc dx, bp
;     pushf

;     stc
;     mov bp, 0x00ec
;     mov si, 0x003a
;     adc bp, si
;     pushf

;     stc
;     mov si, 0x00ba
;     mov di, 0x0088
;     adc si, di
;     pushf

;     dump_state

;     stc
;     mov bx, 0x00ff
;     mov cx, 0x0079
;     adc bx, cx
;     pushf

;     stc
;     mov cx, 0x00ec
;     mov dx, 0x00dc
;     adc cx, dx
;     pushf

;     stc
;     mov dx, 0x1234
;     mov bp, 0x5677
;     adc dx, bp
;     pushf

;     stc
;     mov bp, 0x5050
;     mov si, 0x2fae
;     adc bp, si
;     pushf

;     stc
;     mov si, 0x7ff0
;     mov di, 0x000f
;     adc si, di
;     pushf

;     dump_state

;     stc
;     mov bx, 0x6789
;     mov cx, 0x4566
;     adc bx, cx
;     pushf

;     stc
;     mov cx, 0x89ab
;     mov dx, 0x2344
;     adc cx, dx
;     pushf

;     stc
;     mov dx, 0x9abc
;     mov bp, 0x6542
;     adc dx, bp
;     pushf

;     stc
;     mov bp, 0xedcb
;     mov si, 0x5431
;     adc bp, si
;     pushf

;     stc
;     mov si, 0xa987
;     mov di, 0x8764
;     adc si, di
;     pushf

;     dump_state

;     stc
;     mov bx, 0x8003
;     mov cx, 0xfffb
;     adc bx, cx
;     pushf

;     stc
;     mov cx, 0xffff
;     mov dx, 0xffff
;     adc cx, dx
;     pushf

;     dump_state
